name: CI Pull Request

on:
  pull_request:
    branches: [ main ]

  workflow_dispatch:

env:
  image-name: ghcr.io/francis04j/shift-left-demo:${{ github.sha }}
  image-name-unit-tests: ghcr.io/francis04j/shift-demo-unit-tests:latest

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0
      - name: App [build]
        run: docker build -t ${{ env.image-name }} .

      - name: App [scan]
        uses: azure/container-scan@v0
        with:
          image-name: ${{ env.image-name }}
          severity-threshold: MEDIUM
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GH_CR }}

      - name: Unit tests [build]
        run: docker build --target unit-test -t ${{ env.image-name-unit-tests }} .

      - name: Unit tests [run]
        run: docker run --rm -v ${{ github.workspace }}/path/to/artifacts/testresults:/code/test/DanApi.UnitTests/TestResults ${{ env.image-name-unit-tests }}

      - name: Code coverage [Code Climate]
        uses: paambaati/codeclimate-action@v2.7.5
        env: 
          CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
        with:
          coverageLocations: ${{ github.workspace }}/path/to/artifacts/testresults/coverage.info:lcov
          prefix: /code/
